language: node_js
node_js:
- '10'
before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - npm install jsdoc publish-if-needed npm@latest -g

install:
- npm install jsdoc -g
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/doc.js"
- "./ci/test.js"
after_success:
  - publish-if-needed
env:
  global:
    secure: HQN/QnrzEpw4xpXKW2DM+oyuKxjNnr4hiNRkzm2kxajtKqxuMacH4dUU+bgLjKaos7ZRjDO+Yakpd7177QwZVR9Nm71hgIdFwAbW3IgAyNcYREN0XAt3gqow47zZfYxaJGgLDBvwop643tZjX7B/e1hTsObGJwJXKyaFgVQWWjKX/WSA/FnW9VQTKctF7vEbG4ErlDRPIJTl4KMoyePjBFuOug5aGYp2jqFl9kGoyamlyvIBlecQsPZwLTTPQbsPySItM4SWR+8usFWbXnvqgm5N1acRFCJR0do7rWwyycTS0yOlc0Mh2NxbFo9z4vTbFu/Dsil5FZj+3mlChQjAYA7aBhnM9iJ+rE40pF93g+i3wAHknTNcseb1qUArbVRyARX/oaAQ+23WeGpzKmHF6xFTtiY0f9+WixLTZM7/9X8GPSyx9ziPPV8EMlFxWC3YWcLukXyjJA6Dk+QJHHd14ANJINcDy/B+NIqwoVdEHj6lR11Kgu7gXBeJBD0nXCBpyOxRfkHlbOWuvW0XD3Gxv0JwWGKZSqEYesC766OQ8Xf9uzjwXu8D59l4MWld9/7imAsD3qlDVmGRIYePq6rXjphUUA+UhREhwcWG55EaS1aeRHo5WBRGb0XYsY6qUMMr5l/Pf+1oyAomCqM8TxcYAAx7e6zvwvIE3iQFc4keWqU=
